name: 'Build'
on:
  workflow_dispatch:
    inputs:
      loader:
        type: choice
        description: Mod loader
        options: 
        - fabric
        - forge
      release_type:
        type: choice
        description: Release type
        options: 
        - alpha
        - beta
        - release
  
jobs:
  releaseJar:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache .gradle/caches
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Cache .gradle/wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-wrapper-

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
        continue-on-error: true

      - name: Find JAR artifacts
        run: |
          find . -name "*.jar" -type f
      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v2
        with:
          name: adyeshach Artifact
          path: |
            $(find . -name "*.jar" -type f)
