name: Publish

on:
  workflow_dispatch:
    inputs:
      loader:
        type: choice
        description: Mod loader
        options: 
        - fabric
        - forge
      release_type:
        type: choice
        description: Release type
        options: 
        - alpha
        - beta
        - release

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: :${{ inputs.loader }} -Prelease_type=${{ inputs.release_type }}
    - name: Find JAR artifacts
      run: |
        find . -name "*.jar" -type f
    - name: Upload JAR artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mod-artifact
        path: |
          $(find . -name "*.jar" -type f)
